# Generated by Django 3.0.4 on 2020-03-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
